# Read about configuration here: https://jekyllrb.com/docs/configuration/options/
title: Client Diversity | Ethereum
description: Improve Etheruem's resilience and protect the network by using a minority client.
keywords: ethereum, client, diversity, eth, beacon, chain
url: https://clientdiversity.org
permalink: pretty # Do not change this, it will break all links
timezone: America/New_York
markdown: kramdown
livereload: true
# port: 4400


# Plugins
plugins:
  - jekyll-redirect-from # https://github.com/jekyll/jekyll-redirect-from
redirect_from: # jekyll-redirect-from
  json: false

# Global variables
analytics_tag: |
  <!-- Google tag (gtag.js) -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=G-5YPSBBTM6W"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'G-5YPSBBTM6W');
  </script>

# Notification Bar
enableNotification: false
notificationMsgId: 1 # must increment when creating a new message
notificationMsg: Join the community!<br><a href=""></a>.
notificationExpiration: 3000000000 # epoch time in seconds

# Toast
enableToast: true
toastMsgId: 1 # must increment when creating a new message
toastTitle: We need your help!
toastMsg: Support [Consensus Layer Withdrawal Protection](https://twitter.com/ethStaker/status/1643384655670833153) to help frontrun hackers that have compromised validator withdrawal addresses! # Best when under 100 characters
toastLink: https://github.com/benjaminchodroff/ConsensusLayerWithdrawalProtection#consensus-layer-withdrawal-protection # Optional, leave blank to omit
toastExpiration: 1681516800 # epoch time in seconds

# Navigation
nav_enabled: true

# Links
github_repo: https://github.com/etheralpha/clientdiversity-org

