# Read about configuration here: https://jekyllrb.com/docs/configuration/options/
title: Client Diversity | Ethereum
description: Improve Etheruem's resilience and protect the network by using a minority client.
keywords: ethereum, client, diversity, eth, beacon, chain
url: https://clientdiversity.org
permalink: pretty # Do not change this, it will break all links
timezone: America/New_York
markdown: kramdown
livereload: true
# port: 4400


# Plugins
plugins:
  - jekyll-redirect-from # https://github.com/jekyll/jekyll-redirect-from
redirect_from: # jekyll-redirect-from
  json: false

# Global variables
analytics_tag: |
  <!-- Google tag (gtag.js) -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=G-5YPSBBTM6W"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'G-5YPSBBTM6W');
  </script>

# Notification Bar
enable_notification: false
notification_msg_id: 1 # must increment when creating a new message
notification_msg: Join the community! <br><a href=""></a>.
notification_expiration: 3000000000 # epoch time in seconds

# Toast
enable_toast: true
toast_msg_id: 3 # must increment when creating a new message
toast_title: Lodestar User Incentive Program
toast_msg: Try out Lodestar and promote client diversity for a chance at a prize pool of $25,000 USD! # Best when under 200 characters
toast_link: https://blog.chainsafe.io/introducing-the-lodestar-user-incentive-program-bbaeaa3246eb # Optional, leave blank to omit
toast_link_text: Learn more
# August 23rd, 00:00:00 GMT+0
toast_expiration: 1692748800 # epoch time in seconds

# Navigation
nav_enabled: true

# Links
github_repo: https://github.com/etheralpha/clientdiversity-org

